[tools]
node = "18"

[tasks.up]
run = [
    "docker run --rm -u \"$(id -u):$(id -g)\" -v \"$(pwd):/var/www/html\" -w \"/var/www/html\" laravelsail/php83-composer:latest composer install --ignore-platform-reqs",
    "./vendor/bin/sail up -d",
    "./vendor/bin/sail artisan migrate",
    "./vendor/bin/sail artisan key:generate",
    "npm ci",
    "npm run dev",
]
