name: CI

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mariadb.test:
        image: "mariadb:10"
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: "input"
          MYSQL_USER: "sail"
          MYSQL_PASSWORD: "password"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.dev.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Install NPM Dependencies
        run: npm ci

      - run: npm run build

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PestPHP
        env:
          DB_PORT: ${{ job.services['mariadb.test'].ports[3306] }}
          DB_HOST: 127.0.0.1
        run: vendor/bin/pest

  vitest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install NPM Dependencies
        run: npm ci

      - run: npm run build

      - name: "Run Test Suite with Coverage Report"
        run: npm run coverage
        env:
          LARAVEL_BYPASS_ENV_CHECK: 1
